# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Nov  6 10:30:08 PST 2012
#
#/ usage: mysql:run-script [ --user|-u <anthony>] [ --password|-p <>] [ --host|-h <localhost>] [ --port|-p <3306>]  --script|-s <> 

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print SYNTAX and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo >&2 -e """SYNTAX: $*"""
    else echo >&2 "SYNTAX: $*" 
    fi
    exit 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_usage
}

# options: [user password host port script]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        --user|-u) rerun_option_check $# ; USER=$2 ; shift ;;
        --password|-p) rerun_option_check $# ; PASSWORD=$2 ; shift ;;
        --host|-h) rerun_option_check $# ; HOST=$2 ; shift ;;
        --port|-p) rerun_option_check $# ; PORT=$2 ; shift ;;
        --script|-s) rerun_option_check $# ; SCRIPT=$2 ; shift ;;
        # help option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$USER" ] && USER="anthony"
[ -z "$HOST" ] && HOST="localhost"
[ -z "$PORT" ] && PORT="3306"
# Check required options are set
[ -z "$SCRIPT" ] && { echo >&2 "missing required option: --script" ; return 2 ; }
# If option variables are declared exportable, export them.

#
return 0
