#!/usr/bin/env bash
#
#/ command: mysql:erase: "Erase the MySQL server packages from the system"
#
#/ usage: rerun mysql:erase [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: mysql:erase. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/erase/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/erase/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Remove the MySQL server package and its dependencies from the system:
rerun rpm:erase  --package-name mysql-server

exit $?

# Done
