#!/usr/bin/env bash
#
#/ command: mysql:remove: "Remove the MySQL installation from the system"
#
#/ usage: rerun mysql:remove [ --cleanup <false>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: CLEANUP

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: mysql:remove. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/remove/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/remove/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Stop the MySQL server:
rerun mysql:stop

# Remove the MySQL server package and its dependencies from the system:
sudo yum --quiet -y remove mysql-server

# Cleanup remaining files, if required:
if [[ $CLEANUP = "true" ]]
then
  sudo rm -rf /var/lib/mysql
  sudo rm -f /var/log/mysqld.log.rpmsave
fi

exit $?

# Done
